// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUjb4YIy7WOAbWxLKIEbX5IKTkj8uIeTw',
    appId: '1:87655672816:web:8028b01c543b557b4d4b35',
    messagingSenderId: '87655672816',
    projectId: 'yah-kuza',
    authDomain: 'yah-kuza.firebaseapp.com',
    databaseURL: 'https://yah-kuza.firebaseio.com',
    storageBucket: 'yah-kuza.appspot.com',
    measurementId: 'G-Z7WT7ZMWXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYMy5CTzTrTrt8lub6vGqx7GeP4EcuN1M',
    appId: '1:87655672816:android:9c773f0f3b29211c4d4b35',
    messagingSenderId: '87655672816',
    projectId: 'yah-kuza',
    databaseURL: 'https://yah-kuza.firebaseio.com',
    storageBucket: 'yah-kuza.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4gr5IbSIdnzl3D-sgfeB0qHtnGa9zt1E',
    appId: '1:87655672816:ios:11b9d6a74afc06b24d4b35',
    messagingSenderId: '87655672816',
    projectId: 'yah-kuza',
    databaseURL: 'https://yah-kuza.firebaseio.com',
    storageBucket: 'yah-kuza.appspot.com',
    iosClientId: '87655672816-4qdm3flrtovo6g62c287duqqe92fonoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionEdit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4gr5IbSIdnzl3D-sgfeB0qHtnGa9zt1E',
    appId: '1:87655672816:ios:f6be92191c01b33d4d4b35',
    messagingSenderId: '87655672816',
    projectId: 'yah-kuza',
    databaseURL: 'https://yah-kuza.firebaseio.com',
    storageBucket: 'yah-kuza.appspot.com',
    iosClientId: '87655672816-r7mdt8m5rmo7qrt674h0so0d2p51p2a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.visionEdit.RunnerTests',
  );
}
